config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  devise_for :users
  root to: 'photos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :photos
  resources :bands
  resources :albums, only: %i[destroy new create]
  resources :tracks, only: %i[new create destroy]
  resources :contacts, only: [:new, :create]
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band
  has_many :tracks, dependent: :destroy
  validates :name, :genre, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :user, optional: true
  has_many :albums
  has_one_attached :image
  has_many :tracks, through: :album
  validates :name, presence: true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, validate: true
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact - Captain Films",
      :to => "ben.saintviteux@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :image
  validates :title, :image, :category, presence: true
  validates :title, uniqueness: true
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album
  has_one_attached :audio
  validates :title, :audio, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :photos
  has_many :bands
  has_many :albums, through: :bands
  validates :email, :password, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
    @bands = Band.all
    authorize @album
    authorize @bands
  end

  def create
    @album = Album.new(album_params)
    # @band = Band.where(id: params[:band][:band])
    @album[:band_id] = params[:band][:band]
    # @album.band = @band
    # @album.user = current_user
    authorize @album


    if @album.save!
      redirect_to band_path(@album.band)
    else
      render :new
    end
  end

  def destroy
  end

  private

  def album_params
    params.require(:album).permit(:name, :genre, :release_year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!, only: [:new]
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def random_song
    @tracks = Track.all
    @random_song = @tracks.sample(1)
    @path = CloudinaryHelper.cl_video_path(@random_song)

    return @path
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  helper_method :random_song
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :find_band, only: [:show, :destroy, :edit, :update, :destroy]

  def index
    @bands = policy_scope(Band)
  end

  def show
    @albums = Album.where(band_id: @band)
    @albums.each do |album|
      @tracks = Track.where(album_id: album)
    end
  end

  def new
    @band = Band.new
    authorize @band
  end

  def create
    @band = Band.new(band_params)
    @band.user = current_user

    authorize @band
    if @band.save!
      redirect_to band_path(@band)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @band.update(band_params)
    authorize @band
    redirect_to bands_path
  end

  def destroy
    @band.destroy
    redirect_to bands_path
  end

  private

  def find_band
    @band = Band.find(params[:id])
    authorize @band
  end

  def band_params
    params.require(:band).permit(:name, :image, :description, :spotify_url, :facebook_url, :youtube_url)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    authorize @contact
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    authorize @contact
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def contact
    @user = User.where(id: 1)
    authorize @user
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, only: [:show, :edit, :destroy, :update]

  def index
    @photos = policy_scope(Photo)
  end

  def show
  end

  def new
    @photo = Photo.new
    authorize @photo
  end

  def create
    @photo = Photo.new(photos_params)
    @photo.user = current_user

    if @photo.save!
      redirect_to root_path
    else
      render :new
    end
    authorize @photo
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_photo
    @photo = Photo.find(params[:id])
    authorize @photo
  end

  def photos_params
    params.require(:photo).permit(:title, :image, :category, :location, :description)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
    @track = Track.new
    @albums = Album.all
    authorize @albums
  end

  def create
    @track = Track.new(tracks_params)
    @album = Album.where(id: params[:track][:album_id])
    @album = @track.album
    authorize @track
    authorize @album

    if @track.save!
      redirect_to bands_path(@album.band)
    else
      render :new
    end
  end

  def destroy
  end

  private

  def tracks_params
    params.require(:track).permit(:title, :audio, :album_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/new.html.erb
<div class='form-container'>
  <h2>Nouvel album</h2>
  <%= simple_form_for @album do |a| %>
    <%= a.input :name, label: "Nom de l\'album" %>
    <%= a.input :genre, label: 'genre'%>
    <%= a.input :release_year, as: :date, html5: true, label: 'Date de sortie'%>
    <%= simple_fields_for :band do |b| %>
      <% b.input :band, collection: @bands%>
    <% end %>
    <%= a.submit 'Enregistrer nouvel album', class: 'btn btn-success m-3' %>
  <% end %>
</div>

app/views/bands/edit.html.erb
<div class='form-container'>
  <h2>Éditer artiste</h2>
  <%= simple_form_for @band do |f| %>
    <%= f.input :name, label: "Nom du groupe" %>
    <%= f.input :image, as: :file %>
    <%= f.input :description, as: :text %>
    <%= f.input :spotify_url, label: "Url Spotify" %>
    <%= f.input :facebook_url, label: "Url Facebook" %>
    <%= f.input :youtube_url, label: "Url Youtube" %>
    <%= f.submit 'Enregistrer changements', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/bands/index.html.erb
<div class='bands-container'>
  <h1>Music Projects</h1>
  <%= @bands.each do |band| %>
    <div class='band-title'>
      <h2><%= band.name.upcase %></h2>
    </div>
    <div class='band-container'>
      <div class='band-img' data-id= "<%= band.id %>" >
        <%= link_to cl_image_tag(band.image.key), band_path(band) %>
      </div>
      <div class='band-description slide-in' data-id= "<%= band.id %>">
        <p><%= band.description %></p>
        <div class="links">
          <a class='sm-link' href="<%= band.spotify_url%>" target="_blank" %><i class="fa-brands fa-spotify display2"></i></a>
          <a class='sm-link' href="<%= band.facebook_url%>" target="_blank" %><i class="fa-brands fa-facebook-square"></i></a>
          <a class='sm-link' href="<%= band.youtube_url%>" target="_blank" %><i class="fa-brands fa-youtube-square"></i></a>
        </div>
        <div class="play-music">
          <%# <button onclick="playSong()" class='nav-btn p-2'> Play random song</button> %>
        </div>
      </div>
    </div>
      <% if policy(:band).destroy? %>
        <%= link_to "Delete #{band.name}", band_path(band), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-success m-3' %>
      <% end %>
      <% if policy(:band).update? %>
        <%= link_to "Edit #{band.name}", edit_band_path(band), class: 'btn btn-success m-3' %>
      <% end %>
  <% end %>
</div>

<%= javascript_pack_tag 'bands.js' %>

app/views/bands/new.html.erb
<div class='form-container'>
  <h2>Nouvel artiste</h2>
  <%= simple_form_for @band do |f| %>
    <%= f.input :name, label: "Nom du groupe" %>
    <%= f.input :image, as: :file %>
    <%= f.input :description, as: :text %>
    <%= f.input :spotify_url, label: "Url Spotify" %>
    <%= f.input :facebook_url, label: "Url Facebook" %>
    <%= f.input :youtube_url, label: "Url Youtube" %>
    <%= f.submit 'Enregistrer nouvel artiste', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/bands/show.html.erb
<div class='bands-container'>
  <div class='band-container'>
    <h1><%= @band.name %></h1>
      <div class="band-img">
        <%= cl_image_tag(@band.image.key) %>
      </div>
  <% if policy(:band).destroy? %>
    <%= link_to "Delete #{@band.name}", band_path(@band), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-success m-3' %>
  <% end %>
  <% if policy(:band).update? %>
    <%= link_to "Update #{@band.name}", band_path(@band), method: :update, data: { confirm: "Are you sure?" }, class: 'btn btn-success m-3' %>
  <% end %>

  </div>
</div>

app/views/contacts/create.html.erb
<div class="form-container">
  <h1>Get back to you ASAP!</h1>

  <h3>Thank you for your message!</h3>
</div>

app/views/contacts/new.html.erb
<div class="form-container">
  <h1>Any question ? Want to team up ? </h1>
  <div class='contact-form'>
    <%= simple_form_for @contact do |f| %>
      <div class="col-md-6">
        <%= f.label :name, class:'label' %></br>
        <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :email, class:'label' %></br>
        <%= f.text_field :email, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :message, class:'label' %></br>
        <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area p-2",
              placeholder: "What do you want to talk about?"%></br>

        <div class= "d-none">
          <%= f.label :nickname %>
          <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
        </div>

        <%= f.submit 'Send message 🗞🕊', class: 'nav-btn p-2' %>
      </div>
    <% end %>
  </div>
</div>

<%# Pour mettre en production : https://gist.github.com/stevecondylios/16a53b73f22621e3cde2e17096dbf5ca  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Captain Films - Content Creator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('cffavicon.jpg') %>
    <%= javascript_pack_tag 'hello_vue' %>
  </head>

  <body>
    <% if !current_user.nil? && current_user.admin %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/banner' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%# <%= render 'shared/music-player' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/index.html.erb
<div class='bands-container' id="photos">
  <h1>Film Photography</h1>
  <div class="photos-container background">
    <% counter = 1 %>
    <% @photos.each do |photo| %>
    <div class='photo-container'>
      <div class="photo" data-id="<%=counter%>">
        <%= cl_image_tag(photo.image.key, class: 'photo-img')%>
      </div>
      <div class="photo-description">
        <ul>
          <li><h3><%= photo.title %></h3></li>
          <li><%= photo.location %></li>
          <li class='quote'><%= photo.description %></li>
        </ul>
      </div>
    </div>
    <% counter += 1 %>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'photos.js' %>

app/views/photos/new.html.erb
<div class='form-container'>
  <h2>Nouvelle photo</h2>
  <%= simple_form_for @photo do |f| %>
    <%= f.input :image, as: :file %>
    <%= f.input :title, label: "Title" %>
    <%= f.input :location, label: "Location" %>
    <%= f.input :category, label: "Category" %>
    <%# <%= f.input :category, collection: ['By the Seas', 'Here, There & Everywhere', 'Portraits', 'Live Music', 'Wild Life'], value_method: :second, as: :check_boxes %>
    <%= f.input :description, as: :text %>
    <%= f.submit 'Enregistrer nouvelle photo', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <nav id="nav">
    <ul class='menu'>
        <li class='film'>
          <% if params[:controller] == 'photos' %>
            <%= link_to 'FILM PHOTOGRAPHY 📸', root_path, class:'nav-btn active navbar-font' %>
          <% else %>
            <%= link_to 'FILM PHOTOGRAPHY 📸', root_path, class:'nav-btn navbar-font' %>
          <% end %>
        </li>
        <li class='music'>
        <% if params[:controller] == 'bands' %>
          <%= link_to 'MUSIC', bands_path, class:'nav-btn active navbar-font'%></li>
        <% else %>
          <%= link_to 'MUSIC', bands_path, class:'nav-btn navbar-font'%></li>
        <% end %>
          <input type="button" value="Play me 🔊" class = 'nav-btn navbar-font play-btn'>
        <li class='play'>
          <audio id="audio-navbar" src="https://res.cloudinary.com/benstvit/video/upload/v1649850611/development/4vli2dz4s49rl0zwpabfjm5st4va.mp3"></audio>
        </li>
        <li class='contact'>
          <% if params[:controller] == 'contact' %>
            <%= link_to 'CONTACT', new_contact_path , class:'nav-btn active navbar-font' %>
          <% else %>
            <%= link_to 'CONTACT', new_contact_path , class:'nav-btn navbar-font' %>
          <% end %>
        </li>
    </ul>
    <ul class='sub-menu'>
      <ul class='dropdown-photos dropdown1'>
        <li><a href='#'>Here, There & Everywhere</a></li>
        <li><a href='#'>By The Seas</a></li>
        <li><a href='#'>Portraits</a></li>
        <li><a href='#'>Live Music</a></li>
      </ul>
    </ul>
  </nav>
</div>
<%= javascript_pack_tag 'banner.js' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<div class="container">
  <% flash.each do |key, message| %>
    <p class="alert alert-<%= key %>"><%= message %></p>
  <% end %>
</div>

app/views/shared/_music-player.html.erb
<div class="player">

	<!-- Define the section for displaying details -->
	<div class="details">
	<%# <div class="now-playing">PLAYING x OF y</div> %>
	<div class="track-art"></div>
	<div class="track-name">Track Name</div>
	<div class="track-artist">Track Artist</div>
	</div>

	<!-- Define the section for displaying track buttons -->
	<div class="buttons">
	<div class="prev-track" onclick="prevTrack()">
		<i class="fa fa-step-backward fa-2x"></i>
	</div>
	<div class="playpause-track" onclick="playpauseTrack()">
		<i class="fa fa-play-circle fa-5x"></i>
	</div>
	<div class="next-track" onclick="nextTrack()">
		<i class="fa fa-step-forward fa-2x"></i>
	</div>
	</div>

	<!-- Define the section for displaying the seek slider-->
	<div class="slider_container">
	<div class="current-time">00:00</div>
	<input type="range" min="1" max="100"
		value="0" class="seek_slider" onchange="seekTo()">
	<div class="total-duration">00:00</div>
	</div>

	<!-- Define the section for displaying the volume slider-->
	<div class="slider_container">
	<i class="fa fa-volume-down"></i>
	<input type="range" min="1" max="100"
		value="99" class="volume_slider" onchange="setVolume()">
	<i class="fa fa-volume-up"></i>
	</div>
</div>

<!-- Load the main script for the player -->
<%= javascript_pack_tag 'main.js' %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag ('cffavicon.jpg') %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag ('ben.jpg'), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Photos/Add photo", new_photo_path, class: "dropdown-item" %>
              <%= link_to "Music/Add band ", new_band_path, class: "dropdown-item" %>
              <%= link_to "Music/Add album ", new_album_path, class: "dropdown-item" %>
              <%= link_to "Music/Add track ", new_track_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tracks/new.html.erb
<div class='form-container'>
  <h2>Importer tracks</h2>
  <div class='number-of-tracks'>
    <label for="tracks">Nombre de tracks à ajouter ?</label>
    <input type="number" id="tracks" name="tracks"
        min="1" max="30">
  </div>
  <%= simple_form_for @track do |a| %>
    <%= a.input :title, label: "Nom de la chanson" %>
    <%= a.input :album_id, collection: @albums, label: "Album de la chanson"%>
    <%= a.input :audio, as: :file %>
    <%# <%= a.input :title, label: "Nom de la chanson", data: { id: 1 } %>
    <%# a.input :album_id, collection: @albums, label: "Album de la chanson", data: { id: 1 }%>
    <%# a.input :audio, as: :file, data: { id: 1 } %>
    <%= a.submit 'Enregistrer', class: 'btn btn-success m-3' %>
  <% end %>
</div>

<script>
  const input = document.querySelector('input')
  const audio_form = parseInt(document.querySelector('.simple_form'))

  function countInputs(e) {
    // Duplicate and give dataset id to each title/album/audio trio and then display or not depending on input.
  }

  input.addEventListener('input', countInputs)
</script>